# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: master branch build

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - uses: actions/upload-artifact@v2.1.4
        with:
          name: terraform-generator
          path: terraform-generator-shell/build/libs
      - name: Download launch4j
        run: wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.12
      - name: Make exe
        run: launch4j ./launch4j/config.xml